[pytest]
pythonpath = .
asyncio_mode = auto
asyncio_default_fixture_loop_scope = session
asyncio_default_test_loop_scope = session
markers =
    db_test
    db_normal_case
    db_exception_case
    schemas_test
    api_test
    api_test_get
    api_test_post
    api_test_put
    api_test_delete